force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount (website)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Amount_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Amount_Calculation__c</fullName>
    <label>Amount (Calculation)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Under Discussion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Property Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PropertySearchControllerTest.cls
@isTest
global class PropertySearchControllerTest {

    @testSetup
    public static void setupMethod(){
        Property__c propertyData = new Property__c();
        propertyData.Name = 'Test Property';
        propertyData.Amount__c = '10L';
        propertyData.Title__c = 'Commercial';
        propertyData.Address__Street__s = 'Vaishali Nagar';
        propertyData.Address__City__s = 'Ajmer';
        propertyData.Address__PostalCode__s = '305001';
        propertyData.Status__c = 'Active';
        propertyData.Amount_Calculation__c = 100000;
        Insert propertyData;
    }
    
    @isTest
    public static void getPropertyTest(){
        //Test.setMock(HttpCalloutMock.class, new PropertySearchHttpCalloutMock());
        Property__c propertyData = [Select Id, Name, Amount__c,Title__c From Property__c LIMIT 1];
        PropertySearchController.getDefaultProperties();
        PropertySearchController.getPropertyData(propertyData.Title__c, new List<String>{''}, '100000', '', '','','');
        PropertySearchController.getRecordTypeNames();
        PropertySearchController.getTitlePickListValue('Title__c');
        GeoCodeApiResult g = new GeoCodeApiResult();
    }

}