force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount (website)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Under Discussion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Property Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MapPropertyControllerTest.cls
@isTest
public class MapPropertyControllerTest {
    
    @TestSetup
    public static void testSetupData(){
        Property__c propertyData = new Property__c();
        propertyData.Name = 'Test Property';
        propertyData.Amount__c = '10L';
        propertyData.Title__c = 'Commercial';
        propertyData.Address__Street__s = 'Vaishali Nagar';
        propertyData.Address__City__s = 'Ajmer';
        propertyData.Address__PostalCode__s = '305001';
        propertyData.Address__Latitude__s = 26.41364;
        propertyData.Address__Longitude__s = 74.6496061;
        propertyData.Status__c = 'Active';
        Insert propertyData;
        
        Blob blobBody = Blob.valueOf('Testing TestContentVersion');
        ContentVersion contentVersionObj = new ContentVersion(Title = 'Test',
                                                              Description = 'Test Description',
                                                              PathOnClient ='Test.jpg',
                                                              VersionData = blobBody);
        insert contentVersionObj;
        contentVersionObj = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE ID =: contentVersionObj.Id LIMIT 1];
        
        ContentDocumentLink contentlink = new ContentDocumentLink();
        contentlink.LinkedEntityId = propertyData.Id;
        contentlink.ContentDocumentId = contentVersionObj.ContentDocumentId;
        contentlink.ShareType = 'V';
        contentlink.Visibility = 'AllUsers'; 
        insert contentlink ;
    }
    
    @isTest
    public static void getPropertiesTest(){
        Property__c propertyData = [Select Id From Property__c LIMIT 1];
        MapPropertyController propertyController = new MapPropertyController();
        ApexPages.StandardController sc = new ApexPages.StandardController(propertyData);
        propertyController = new MapPropertyController(sc);
        MapPropertyController.getProperty(propertyData.Id);
        
    }
}