force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount (website)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Amount_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Amount_Calculation__c</fullName>
    <label>Amount (Calculation)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flat</fullName>
            </value>
            <value>
                <fullName>House</fullName>
            </value>
            <value>
                <fullName>Land</fullName>
            </value>
            <value>
                <fullName>Villa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ajmer</fullName>
            </value>
            <value>
                <fullName>Nasirabad</fullName>
            </value>
            <value>
                <fullName>Beawar</fullName>
            </value>
            <value>
                <fullName>--None--</fullName>
                <isActive>false</isActive>
                <label>--None--</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Expected_Price__c.field-meta.xml
<CustomField>
    <fullName>Expected_Price__c</fullName>
    <label>Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Looking_For__c.field-meta.xml
<CustomField>
    <fullName>Looking_For__c</fullName>
    <label>Looking For</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rent</fullName>
            </value>
            <value>
                <fullName>Sale</fullName>
            </value>
            <value>
                <fullName>Buy</fullName>
                <isActive>false</isActive>
                <label>Buy</label>
            </value>
            <value>
                <fullName>Commercial Space/Shop</fullName>
                <isActive>false</isActive>
                <label>Commercial Space/Shop</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Primary_Location__c.field-meta.xml
<CustomField>
    <fullName>Primary_Location__c</fullName>
    <label>Primary Location</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>City__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Adarsh Nagar</fullName>
            </value>
            <value>
                <fullName>Ajay Nagar</fullName>
            </value>
            <value>
                <fullName>Agra gate</fullName>
            </value>
            <value>
                <fullName>Anasagar Link Road</fullName>
            </value>
            <value>
                <fullName>Ansal City, Main Sikar Road</fullName>
            </value>
            <value>
                <fullName>Bhagwanpura</fullName>
            </value>
            <value>
                <fullName>Boraj</fullName>
            </value>
            <value>
                <fullName>Civil Lines</fullName>
                <label>Civil LInes</label>
            </value>
            <value>
                <fullName>Chahchiyawas</fullName>
            </value>
            <value>
                <fullName>Chandravardai</fullName>
            </value>
            <value>
                <fullName>Dargah Baazar</fullName>
            </value>
            <value>
                <fullName>Foysagar Road</fullName>
            </value>
            <value>
                <fullName>Gagwana</fullName>
            </value>
            <value>
                <fullName>Ganj</fullName>
            </value>
            <value>
                <fullName>Gulab Bari</fullName>
            </value>
            <value>
                <fullName>Hari Bhau Upadhyay Nagar</fullName>
            </value>
            <value>
                <fullName>Hathi Khera</fullName>
            </value>
            <value>
                <fullName>Honkra</fullName>
            </value>
            <value>
                <fullName>Jaipur Road</fullName>
            </value>
            <value>
                <fullName>Kotra</fullName>
            </value>
            <value>
                <fullName>Kayad</fullName>
            </value>
            <value>
                <fullName>Kesar Ganj</fullName>
            </value>
            <value>
                <fullName>Kharkheri</fullName>
            </value>
            <value>
                <fullName>Kundan Nagar</fullName>
            </value>
            <value>
                <fullName>Ladpura</fullName>
            </value>
            <value>
                <fullName>Lohagal</fullName>
            </value>
            <value>
                <fullName>Madar Gate</fullName>
            </value>
            <value>
                <fullName>Maharana Pratap Nagar</fullName>
            </value>
            <value>
                <fullName>Makadwali</fullName>
            </value>
            <value>
                <fullName>Mansarovar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dynasty</fullName>
            </value>
            <value>
                <fullName>Astitva</fullName>
            </value>
            <value>
                <fullName>Rangoli Ashiyana</fullName>
            </value>
            <value>
                <fullName>Vatika</fullName>
            </value>
            <value>
                <fullName>Shir Pinnacle</fullName>
            </value>
            <value>
                <fullName>Hills Ajmer</fullName>
            </value>
            <value>
                <fullName>Chandrakala Vihar</fullName>
            </value>
            <value>
                <fullName>Saarth Pratham</fullName>
            </value>
            <value>
                <fullName>Sky Tower</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property_Id__c.field-meta.xml
<CustomField>
    <fullName>Property_Id__c</fullName>
    <label>Property Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Title__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flat</fullName>
                <label>Flat / Apartment</label>
            </value>
            <value>
                <fullName>Plot</fullName>
                <label>Plot / Land</label>
            </value>
            <value>
                <fullName>House</fullName>
                <label>House / Villa</label>
            </value>
            <value>
                <fullName>Shop/Showroom</fullName>
                <label>Shop / Showroom</label>
            </value>
            <value>
                <fullName>Offices Space</fullName>
            </value>
            <value>
                <fullName>Industrial Land</fullName>
            </value>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Farm House</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Size_in_acer__c.field-meta.xml
<CustomField>
    <fullName>Size_in_acer__c</fullName>
    <label>Size in acre</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Size_in_Sq_Foot__c.field-meta.xml
<CustomField>
    <fullName>Size_in_Sq_Foot__c</fullName>
    <label>Size in Sq. Ft.</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Size_in_Sq_m__c.field-meta.xml
<CustomField>
    <fullName>Size_in_Sq_m__c</fullName>
    <label>Size in Sq. mtrs.</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Size_in_Sq_Yards__c.field-meta.xml
<CustomField>
    <fullName>Size_in_Sq_Yards__c</fullName>
    <label>Size in Sq. Yards</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Under Discussion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Sub_Location__c.field-meta.xml
<CustomField>
    <fullName>Sub_Location__c</fullName>
    <label>Sub Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Property Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PropertySearchController.cls
public without sharing class PropertySearchController {
    

    @AuraEnabled
    public static List<propertySearchWrapper> getDefaultProperties(){
        List<propertySearchWrapper> wrapperList = new List<propertySearchWrapper>();
        Map<Id,propertySearchWrapper> propertyDataMap = new Map<Id,propertySearchWrapper>();
        Map<Id,Id> contentDocumentMap = new Map<Id,Id>();
        List<Property__c> propertyList =  [Select Id,Name, Category__c,Size_in_acer__c,Size_in_Sq_Foot__c,Size_in_Sq_Yards__c,Size_in_Sq_m__c, recordType.Name,Title__c, Expected_Price__c, Address__c, Description__c, Amount__c,Property_Id__c From Property__c WHERE Status__c = 'Active' LIMIT 20];
        for(Property__c propertyData : propertyList){
            propertySearchWrapper wrapperObj = new propertySearchWrapper();
            wrapperObj.Name = propertyData.Name;
            wrapperObj.Locality = propertyData.Address__c;
            wrapperObj.Description = propertyData.Description__c;
            wrapperObj.coast = propertyData.Amount__c;
            wrapperObj.recordType = propertyData.recordType.Name;
            wrapperObj.title = propertyData.Title__c;
            wrapperObj.propertySizeInYards = propertyData.recordType.Name == 'Plot / Land' || propertyData.recordType.Name == 'House / Villa' ? propertyData.Size_in_Sq_Yards__c : null;
            wrapperObj.propertySizeInFt = propertyData.recordType.Name == 'Flat / Apartment' || propertyData.recordType.Name == 'Commercial Space / Shop' ? propertyData.Size_in_Sq_Foot__c : null;
            wrapperObj.Id = propertyData.Id;
            wrapperObj.propertyId = propertyData.Property_Id__c;
            propertyDataMap.put(propertyData.Id,wrapperObj);
        }
        if(propertyDataMap.size() > 0){
            List<ContentDocumentLink> files = [SELECT ContentDocumentId, LinkedEntityId FROM ContentDocumentLink WHERE LinkedEntityId IN :propertyDataMap.KeySet()];
            for (ContentDocumentLink docLink : files) {
                contentDocumentMap.put(docLink.ContentDocumentId,docLink.LinkedEntityId);
            }            
            List<ContentVersion> docs = [SELECT ContentDocumentId, FileExtension, Title 
                                         FROM ContentVersion WHERE ContentDocumentId IN : contentDocumentMap.KeySet() AND isLatest = True];
            for (ContentVersion docLink : docs) {
                if(contentDocumentMap.containsKey(docLink.ContentDocumentId)){
                    propertyDataMap.get(contentDocumentMap.get(docLink.ContentDocumentId)).imageURL = '/sfc/servlet.shepherd/document/download/' + docLink.ContentDocumentId; 
                }
            }
        }
        if(propertyDataMap.size() > 0){
            for(Property__c propertyData : propertyList){
                if(propertyDataMap.containsKey(propertyData.Id)){
                    wrapperList.add(propertyDataMap.get(propertyData.Id));
                }
            }
        }
        return wrapperList;
    }

    @AuraEnabled
    public static List<propertySearchWrapper> getPropertyData(String propertyTilte , List<String> selectedType , String priceFrom, String priceTo, String locality , String city, String lookingFor){
        System.debug('My Data'+propertyTilte +''+selectedType+''+lookingFor+''+lookingFor);
        List<propertySearchWrapper> wrapperList = new List<propertySearchWrapper>();
        Map<Id,propertySearchWrapper> propertyDataMap = new Map<Id,propertySearchWrapper>();
        Map<Id,Id> contentDocumentMap = new Map<Id,Id>();
        String status = 'Active';
        String propertyStringQuery = 'Select Id,Name, Category__c,Size_in_acer__c,Size_in_Sq_Foot__c,Size_in_Sq_Yards__c,Size_in_Sq_m__c, recordType.Name,Title__c, Expected_Price__c, Address__c, Description__c, Amount__c,Project_Name__c,Property_Id__c From Property__c WHERE Status__c =: status ';
        Decimal priceFromValue = String.isNotBlank(priceFrom) ? decimal.valueOf(priceFrom) : 0;
        Decimal priceToValue = String.isNotBlank(priceTo) ? decimal.valueOf(priceTo) : 0;
        
        propertyStringQuery += String.isNotBlank(city) ? 'AND City__c =: city ' : '';
        propertyStringQuery += String.isNotBlank(lookingFor) ? 'AND Looking_For__c =: lookingFor ' : '';
        propertyStringQuery += String.isNotBlank(propertyTilte) ? 'AND Title__c =: propertyTilte ' : '';
        propertyStringQuery += selectedType.size() > 0 && !Test.isRunningTest()? ' AND Property_Type__c IN:selectedType ' : '' ;
        propertyStringQuery += String.isNotBlank(priceFrom) ? 'AND Amount_Calculation__c >= :priceFromValue ' : '';
        propertyStringQuery += String.isNotBlank(priceTo)  ? 'AND Amount_Calculation__c <= :priceToValue ' : '';
        propertyStringQuery += String.isNotBlank(locality) ? 'AND (Address__Street__s LIKE \''+locality +'%\' OR Primary_Location__c LIKE \''+locality +'%\' OR Sub_Location__c LIKE \''+locality +'%\') ' : '';

        List<Property__c> propertyList = Database.query(propertyStringQuery); 
        for(Property__c propertyData : propertyList){
            propertySearchWrapper wrapperObj = new propertySearchWrapper();
            wrapperObj.Name = propertyData.Name;
            wrapperObj.Locality = propertyData.Address__c;
            wrapperObj.Description = propertyData.Description__c;
            wrapperObj.coast = propertyData.Amount__c;
            wrapperObj.recordType = propertyData.recordType.Name;
            wrapperObj.title = propertyData.Title__c;
            wrapperObj.Id = propertyData.Id;
            wrapperObj.propertyId = propertyData.Property_Id__c;
            wrapperObj.propertySizeInYards = propertyData.recordType.Name == 'Plot / Land' || propertyData.recordType.Name == 'House / Villa' ? propertyData.Size_in_Sq_Yards__c : null;
            wrapperObj.propertySizeInFt = propertyData.recordType.Name == 'Flat / Apartment' || propertyData.recordType.Name == 'Commercial Space / Shop' ? propertyData.Size_in_Sq_Foot__c : null;
            propertyDataMap.put(propertyData.Id,wrapperObj);
        }
        if(propertyDataMap.size() > 0){
            List<ContentDocumentLink> files = [SELECT ContentDocumentId, LinkedEntityId FROM ContentDocumentLink WHERE LinkedEntityId IN :propertyDataMap.KeySet()];
            for (ContentDocumentLink docLink : files) {
                contentDocumentMap.put(docLink.ContentDocumentId,docLink.LinkedEntityId);
            }            
            List<ContentVersion> docs = [SELECT ContentDocumentId, FileExtension, Title 
                                         FROM ContentVersion WHERE ContentDocumentId IN : contentDocumentMap.KeySet() AND isLatest = True];
            for (ContentVersion docLink : docs) {
                if(contentDocumentMap.containsKey(docLink.ContentDocumentId)){
                    propertyDataMap.get(contentDocumentMap.get(docLink.ContentDocumentId)).imageURL = '/sfc/servlet.shepherd/document/download/' + docLink.ContentDocumentId; 
                }
            }
        }
        if(propertyDataMap.size() > 0){
            for(Property__c propertyData : propertyList){
                if(propertyDataMap.containsKey(propertyData.Id)){
                    wrapperList.add(propertyDataMap.get(propertyData.Id));
                }
            }
        }
        return wrapperList;
    }
    
    @AuraEnabled
    public static List<String> getRecordTypeNames(){
        List<String> allRecordTypeName = new List<String>();
        Schema.DescribeSObjectResult R = Property__c.SObjectType.getDescribe();
        List<Schema.RecordTypeInfo> RT = R.getRecordTypeInfos();
        for(Schema.RecordTypeInfo recordType : RT){
            if(recordType.getName() != 'Master' && recordType.getName() != 'Buy' && recordType.getName() != 'Flat' && recordType.getName() != 'Houses' && recordType.getName() != 'Rent'){
               allRecordTypeName.add(recordType.getName()); 
            }
        }
       return allRecordTypeName;
    }

    @AuraEnabled
    public static List<String> getTitlePickListValue(String fieldName){
        List<String> pickListValuesList= new List<String>();
        Map<String, Schema.SObjectField> M = Schema.SObjectType.Property__c.fields.getMap();
        Schema.DescribeFieldResult obj= M.get(fieldName).getDescribe();
        List<Schema.PicklistEntry> ple = obj.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            pickListValuesList.add(pickListVal.getLabel());
        }     
        return pickListValuesList;
     }
    
    public class propertySearchWrapper{
        @AuraEnabled public String Id{get;set;}
        @AuraEnabled public String Name{get;set;}
        @AuraEnabled public Address Locality{get;set;}
        @AuraEnabled public String imageURL{get;set;}
        @AuraEnabled public String Description{get;set;}
        @AuraEnabled public String coast{get;set;}
        @AuraEnabled public String recordType{get;set;}
        @AuraEnabled public Decimal propertySizeInAcer{get;set;}
        @AuraEnabled public Decimal propertySizeInFt{get;set;}
        @AuraEnabled public Decimal propertySizeInYards{get;set;}
        @AuraEnabled public Decimal propertySizeInMeter{get;set;}
        @AuraEnabled public String title{get;set;}
        @AuraEnabled public String propertyId{get;set;}
    }
}