force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Option_1__c.field-meta.xml
<CustomField>
    <fullName>Option_1__c</fullName>
    <label>Option 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Option_2__c.field-meta.xml
<CustomField>
    <fullName>Option_2__c</fullName>
    <label>Option 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetQuestionsDataControllerTest.cls
@isTest
public class GetQuestionsDataControllerTest {
	
    @isTest
    public static void getQuestionDataTest(){
        Question__c quetionData = new Question__c();
        quetionData.Name = 'Test Question';
        quetionData.Option_1__c = 'test 1';
        quetionData.Option_2__c = 'test 2';
        quetionData.Order_Number__c = 1;
		insert quetionData;
        
        GetQuestionsDataController.getQuestionData();
        GetQuestionsDataController.createEnquiryAndAnswersRecord('{"Name" : "test","Email__c":"test@gmail.com"}','{"TestData":"test"}');
    }
}