force-app/main/default/objects/Customer_Response__c/Customer_Response__c.object-meta.xml
<CustomObject>
    <label>Customer Response</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Customer Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Response__c/fields/Customer_Answer__c.field-meta.xml
<CustomField>
    <fullName>Customer_Answer__c</fullName>
    <label>Customer Answer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Customer_Response__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Name</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipName>Customers_Respnce</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/Enquiry__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Dependet__c.field-meta.xml
<CustomField>
    <fullName>Dependet__c</fullName>
    <label>Dependent Answer</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/fields/Help_Message__c.field-meta.xml
<CustomField>
    <fullName>Help_Message__c</fullName>
    <label>Help Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Option_1__c.field-meta.xml
<CustomField>
    <fullName>Option_1__c</fullName>
    <label>Option 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Option_2__c.field-meta.xml
<CustomField>
    <fullName>Option_2__c</fullName>
    <label>Option 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Option_3__c.field-meta.xml
<CustomField>
    <fullName>Option_3__c</fullName>
    <label>Option 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Option_6__c.field-meta.xml
<CustomField>
    <fullName>Option_6__c</fullName>
    <label>Option 6</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Option_7__c.field-meta.xml
<CustomField>
    <fullName>Option_7__c</fullName>
    <label>Option 7</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Option_8__c.field-meta.xml
<CustomField>
    <fullName>Option_8__c</fullName>
    <label>Option 8</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Parent_Question__c.field-meta.xml
<CustomField>
    <fullName>Parent_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Option</fullName>
            </value>
            <value>
                <fullName>Message</fullName>
            </value>
            <value>
                <fullName>Input</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GetQuestionsDataController.cls
public without sharing class GetQuestionsDataController {

    @AuraEnabled
    public static List<questionDataWrapper> getQuestionData(){
        List<questionDataWrapper> wrapperList = new List<questionDataWrapper>();
        Set<String> options = new Set<string>{'Option_1__c','Option_2__c','Option_3__c','Option_4__c','Option_5__c','Option_6__c','Option_7__c','Option_8__c'};
        List<Question__c> questionDataList = [Select Id, Name, Option_1__c, Option_2__c, Option_3__c, Option_4__c,
                Option_5__c, Option_6__c, Option_7__c, Option_8__c, Order_Number__c, Type__c,Help_Message__c,
                Parent_Question__c, Dependet__c FROM Question__c ORDER BY Order_Number__c ASC];
        
        for(Question__c question : questionDataList){
            questionDataWrapper wrapperObj = new questionDataWrapper();
            wrapperObj.Id = question.Id;
            wrapperObj.Name = question.Name;
           	wrapperObj.orderNumber = question.Order_Number__c;
            wrapperObj.ParentQuestion = question.Parent_Question__c;
            wrapperObj.Dependent = question.Dependet__c;
            wrapperObj.isShowText = false;
            wrapperObj.helpMessage = question.Help_Message__c;
            wrapperObj.isHelp = String.isNotBlank(question.Help_Message__c) ? true : false;
            wrapperObj.isInputshow = question.Type__c == 'Input' ? true:false;
			wrapperObj.options = new List<String>();            
            for(String str : options){
                if(question.get(str) != null){
                    wrapperObj.options.add((String)question.get(str));
                }
            }
            wrapperList.add(wrapperObj);
        }
        return wrapperList;
        
    }

    @AuraEnabled
    public static void createEnquiryAndAnswersRecord(String customerInfo, String answersData){
        Enquiry__c enquiryObj = (Enquiry__c) JSON.deserialize(customerInfo, Enquiry__c.class);
        insert enquiryObj;
        Map<String,String> answersMap = (Map<String,String>) JSON.deserialize(answersData, Map<String,String>.class);
        List<Customer_Response__c> responseList = new List<Customer_Response__c>();
        for(String str : answersMap.keySet()){
            Customer_Response__c response = new Customer_Response__c();
            response.Question__c = str;
            response.Customer_Answer__c = answersMap.get(str);
            response.Customer_Name__c = enquiryObj.Id;
            responseList.add(response);
        }
        if(responseList.size() > 0){
            INSERT responseList;
        }
    }
    
    public class questionDataWrapper{
        @AuraEnabled public String Id{get;set;}
        @AuraEnabled public String Name{get;set;}
        @AuraEnabled public List<String> options{get;set;}
        @AuraEnabled public Decimal orderNumber{get;set;}
        @AuraEnabled public String ParentQuestion{get;set;}
        @AuraEnabled public String Dependent{get;set;}
        @AuraEnabled public String helpMessage{get;set;}
        @AuraEnabled public Boolean isHelp{get;set;}
        @AuraEnabled public Boolean isShowText{get;set;}
        @AuraEnabled public Boolean isInputshow{get;set;}
    }
}